export const LOGIN_USER_PENDING = "LOGIN_USER_PENDING";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_REJECTED = "LOGIN_USER_REJECTED";

export const UPDATE_USER_PENDING = "UPDATE_USER_PENDING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_REJECTED = "UPDATE_USER_SUCCESS";

export const SIGNUP_USER_PENDING = "SIGNUP_USER_PENDING";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_REJECTED = "SIGNUP_USER_REJECTED";

export const GET_USER_PENDING = "GET_USER_PENDING";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_REJECTED = "GET_USER_REJECTED";
