export const GET_TICKETS_PENDING = "GET_TICKETS_PENDING";
export const GET_TICKETS_SUCCESS = "GET_TICKETS_SUCCESS";
export const GET_TICKETS_REJECTED = "GET_TICKETS_REJECTED";

export const CREATE_TICKET_PENDING = "CREATE_TICKET_PENDING";
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_REJECTED = "CREATE_TICKET_REJECTED";
